# Generated by Django 5.2.1 on 2025-05-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст договора')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('duration_days', models.IntegerField(verbose_name='Длительность (дни)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Дата истечения')),
                ('max_uses', models.IntegerField(default=1, verbose_name='Макс. количество использований')),
                ('uses_count', models.IntegerField(default=0, verbose_name='Количество использований')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('tariff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, verbose_name='Описание тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_days', models.IntegerField(verbose_name='Длительность (дни)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
