# Generated by Django 5.2.1 on 2025-05-13 15:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название уровня')),
                ('required_points', models.IntegerField(verbose_name='Необходимое количество баллов')),
                ('description', models.TextField(verbose_name='Описание уровня')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('test_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала теста')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания теста')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильные ответы')),
                ('incorrect_answers', models.IntegerField(default=0, verbose_name='Неправильные ответы')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('difficulty', models.CharField(max_length=50, verbose_name='Сложность')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.level', verbose_name='Уровень сложности')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('hint_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст подсказки')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения подсказки')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Подсказка',
                'verbose_name_plural': 'Подсказки',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='tasks.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('theory_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание теории')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Теория',
                'verbose_name_plural': 'Теории',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Сессия тренажёра',
                'verbose_name_plural': 'Сессии тренажёра',
            },
        ),
    ]
